#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m rule --add app="^(System Settings|系统设置)" manage=off

yabai -m rule --add app="^(Alibaba Cloud Client)$" manage=off

yabai -m rule --add app="^(WeChat|微信)" manage=off

yabai -m rule --add app="^(QQ)" manage=off

yabai -m rule --add app="^(LX Music)" manage=off

yabai -m rule --add app="^(网易邮箱大师)" manage=off

sudo yabai --load-sa

# global settings
yabai -m config \
  mouse_follows_focus off \
  focus_follows_mouse off \
  window_origin_display default \
  window_placement second_child \
  window_zoom_persist on \
  window_shadow on \
  window_animation_duration 0.3 \
  window_opacity_duration 0.3 \
  active_window_opacity 1.0 \
  normal_window_opacity 0.70 \
  window_opacity off \
  insert_feedback_color 0xffd75f5f \
  split_ratio 0.50 \
  split_type auto \
  auto_balance off \
  top_padding 12 \
  bottom_padding 12 \
  left_padding 12 \
  right_padding 12 \
  window_gap 12 \
  layout bsp \
  mouse_modifier alt \
  mouse_action1 move \
  mouse_action2 resize \
  mouse_drop_action swap

borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0 &

echo "yabai configuration loaded.."
