return {
  -- 'dense-analysis/ale',
  -- config = function()
  --   -- Configuration goes here.
  --   local g = vim.g
  --
  --   g.ale_ruby_rubocop_auto_correct_all = 1
  --
  --   g.ale_lint_on_enter = 0
  --   g.ale_lint_on_save = 1
  --   g.ale_lint_on_filetype_changed = 1
  --
  --   g.ale_linters = {
  --     ruby = { 'rubocop', 'ruby' },
  --     lua = { 'lua_language_server' },
  --     javascript = { 'eslint' },
  --     typescript = { 'eslint' },
  --     typescriptreact = { 'eslint' },
  --     javascriptreact = { 'eslint' },
  --     vue = { 'eslint' ,'prettier' },
  --   }
  -- end,
}
